# Generated by Django 5.2 on 2026-03-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='fournisseur',
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='stockpharmacie',
            options={},
        ),
        migrations.AddField(
            model_name='medicament',
            name='quantite_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicament',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicaments', to='stock.categorie'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dci',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='prix_achat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='prix_vente',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockpharmacie',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
