# Generated by Django 5.2 on 2026-04-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_alter_pharmacie_proprietaire'),
        ('stock', '0003_vente_lignevente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stock_faible', 'Stock faible'), ('rupture_stock', 'Rupture de stock'),
                ('expiration', 'Expiration proche'), ('reservation_receperee', 'Réservation reçue')], max_length=20)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], max_length=10)),
                ('destinataire', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stock.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pharmacies.pharmacie')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
