# Generated by Django 5.2 on 2026-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('stock_faible', 'Stock faible'), ('rupture_stock', 'Rupture de stock'), ('expiration', 'Expiration proche'), ('reservation_recuperee', 'Réservation récupérée')], max_length=30),
        ),
    ]
