# Generated by Django 6.0.1 on 2026-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_atc_categorie_atc'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='vecteur_semantique',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
