# Generated by Django 6.0.1 on 2026-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_medicament_vecteur_semantique'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='symptomes_cibles',
            field=models.TextField(blank=True, help_text='Symptômes spécifiques ciblés par le médicament', null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='voie_administration',
            field=models.CharField(blank=True, help_text='Ex: Orale, Cutanée, Ophtalmique', max_length=50, null=True),
        ),
    ]
