# Generated by Django 6.0.1 on 2026-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_medicament_symptomes_cibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='profil_patient',
            field=models.CharField(choices=[('enfant', 'Enfant'), ('adulte', 'Adulte'), ('tous', 'Tous')], default='tous', help_text='Profil ciblé par le médicament', max_length=20),
        ),
    ]
