# Generated by Django 5.2 on 2026-05-06 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_rename_presencepharmacien_userpresence_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessage',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messagerie.group'),
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='message_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messagerie.groupmessage'),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messagerie.conversation'),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messagerie.message'),
        ),
    ]
