# Generated by Django 6.0.1 on 2026-05-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0003_notificationmessage_groupe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationMessage',
        ),
    ]
