# Generated by Django 6.0.1 on 2026-06-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0004_delete_notificationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
