# Generated by Django 6.0.2 on 2026-02-22 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerieTunisie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('type_ferie', models.CharField(choices=[('fixe', 'Fixe'), ('religieux', 'Religieux')], max_length=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeRamadan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.IntegerField(unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='localisations.delegation')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='GardePharmacie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_garde', models.CharField(choices=[('nuit', 'Garde de Nuit'), ('dimanche', 'Garde Dimanche'), ('ferie', 'Garde Jour Férié')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_debut', models.TimeField(default='20:00')),
                ('heure_fin', models.TimeField(default='08:00')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardes', to='pharmacies.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='HoraireTravail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('est_ouvert', models.BooleanField(default=True)),
                ('heure_ouverture', models.TimeField(blank=True, null=True)),
                ('heure_fermeture', models.TimeField(blank=True, null=True)),
                ('pause_debut', models.TimeField(blank=True, null=True)),
                ('pause_fin', models.TimeField(blank=True, null=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='pharmacies.pharmacie')),
            ],
            options={
                'unique_together': {('pharmacie', 'jour')},
            },
        ),
        migrations.CreateModel(
            name='HoraireRamadan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('est_ouvert', models.BooleanField(default=True)),
                ('heure_ouverture_1', models.TimeField(blank=True, null=True)),
                ('heure_fermeture_1', models.TimeField(blank=True, null=True)),
                ('heure_ouverture_2', models.TimeField(blank=True, null=True)),
                ('heure_fermeture_2', models.TimeField(blank=True, null=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_ramadan', to='pharmacies.pharmacie')),
            ],
            options={
                'unique_together': {('pharmacie', 'jour')},
            },
        ),
    ]
