# Generated by Django 6.0.2 on 2026-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardepharmacie',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='gardepharmacie',
            name='heure_fin',
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='categorie',
            field=models.CharField(choices=[('A', 'Catégorie A - Jour (8h30→19h30)'), ('B', 'Catégorie B - Nuit (19h30→8h30)')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='gardepharmacie',
            name='type_garde',
            field=models.CharField(choices=[('jour', 'Garde de Jour A — 8h30 à 19h30'), ('nuit', 'Garde de Nuit B — 19h30 à 8h30'), ('dimanche', 'Garde Dimanche'), ('ferie', 'Garde Jour Férié')], max_length=20),
        ),
    ]
