# Generated by Django 6.0.2 on 2026-02-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_remove_gardepharmacie_heure_debut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gardepharmacie',
            options={'ordering': ['date_debut']},
        ),
        migrations.AlterModelOptions(
            name='perioderamadan',
            options={'ordering': ['-annee']},
        ),
    ]
