# Generated by Django 5.2 on 2026-05-03 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localisations', '0001_initial'),
        ('pharmacies', '0005_demandessuspension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pharmacie',
            constraint=models.UniqueConstraint(condition=models.Q(('proprietaire__isnull', False)), fields=('proprietaire',), name='unique_proprietaire_pharmacie'),
        ),
    ]
