# Generated by Django 6.0.2 on 2026-02-22 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gouvernorat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gouvernorats',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('gouvernorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='localisations.gouvernorat')),
            ],
            options={
                'verbose_name_plural': 'Délégations',
                'ordering': ['gouvernorat__nom', 'nom'],
                'unique_together': {('nom', 'gouvernorat')},
            },
        ),
    ]
