# Generated by Django 5.2 on 2026-03-18 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0003_vente_lignevente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité réservée')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('recuperee', 'Récupérée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='active', max_length=20, verbose_name='Statut')),
                ('expire_at', models.DateTimeField(verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stock.medicament', verbose_name='Médicament')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stock.stockpharmacie', verbose_name='Stock pharmacie')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
