# Generated by Django 5.2 on 2026-05-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('recuperee', 'Récupérée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='active', max_length=20, verbose_name='Statut'),
        ),
    ]
