# Generated by Django 6.0.1 on 2026-05-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expire_at',
            field=models.DateTimeField(db_index=True, verbose_name='Expire le'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('recuperee', 'Récupérée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], db_index=True, default='active', max_length=20, verbose_name='Statut'),
        ),
    ]
