# Generated by Django 6.0.1 on 2026-05-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expire_at',
            field=models.DateTimeField(verbose_name='Expire le'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('recuperee', 'Récupérée'), ('expiree', 'Expirée'), ('annulee', 'Annulée')], default='active', max_length=20, verbose_name='Statut'),
        ),
    ]
