# Generated by Django 5.2 on 2026-04-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active'),
        ('pharmacies', '0005_demandessuspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pharmacies_travail',
            field=models.ManyToManyField(blank=True, related_name='pharmaciens', to='pharmacies.pharmacie'),
        ),
    ]
