# Generated by Django 5.2 on 2026-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_pharmacies_travail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
