# Generated by Django 6.0.1 on 2026-05-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_encoding',
        ),
    ]
