# Generated by Django 5.2 on 2026-03-31 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0003_alter_gardepharmacie_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUrgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('medicament', 'Médicament'), ('service', 'Service')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rayon_km', models.FloatField(default=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_urgentes', to=settings.AUTH_USER_MODEL)),
                ('pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_recues', to='pharmacies.pharmacie')),
            ],
        ),
    ]
